### ISSUE TITLE
[BUG] Subjects not supported for notifications

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#226]
**Describe the bug**
The notification plugin does not have support for adding a subject to a notification. This is already supported in the Alerting plugin. Also this come to be very important for the email channel type since we want to provide a subject there.

**To Reproduce**
N/A

**Expected behavior**
Update ChannelMessage model such that subject is an additional parameter

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**
This breaks parity for customers already using email destinations in Alerting

**Comment by zhongnansu** [comment]
We do have subject for email. Since for any notification type, it will have a "subject", so we created a `title` field in the `EventSource` data model.

https://github.com/opensearch-project/common-utils/blob/d27d52c23c9d66eb2b39dcb85ad22bd868737196/src/main/kotlin/org/opensearch/commons/notifications/model/EventSource.kt#L50

**Comment by lezzago** [comment]
Thanks that is good to know
