### ISSUE TITLE
[BUG] Build is broken

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#260]
**Describe the bug**

```
$ ./gradlew publishToMavenLocal -PexcludeTests="**/SesChannelIT*" -Dopensearch.version=1.0.0
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 6.6.1
  OS Info               : Linux 5.8.0-1035-aws (amd64)
  JDK Version           : 14 (JDK)
  JAVA_HOME             : /usr/lib/jvm/java-14-openjdk-amd64
  Random Testing Seed   : EA3DAD371E88EEC2
  In FIPS 140 mode      : false
=======================================
> Task :notifications:compileKotlin FAILED
e: /home/ubuntu/source/opensearch-project/notifications/upstream-notifications/notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt: (232, 95): Unresolved reference: method

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':notifications:compileKotlin'.
> Compilation error. See log for more details
Not familiar with kotlin, any ideas?
```

I can build on 0742a9118506c0bd3737bd06d35a6ee15d907584, looks like CI agrees, a bunch of commits were merged that have a broken build it looks like?

**Comment by zhongnansu** [comment]
@dblock The CI build failure arise recently, even with merged commits(which passed CI at that time). We created an issue for tracking, but couldn't resolve for 2 days. For the commit your shared, if you re-run the CI on that, it will fail. Same thing applies to the other commits you saw that shows with broken build, because I re-run them previously when identifying the issue.

https://github.com/opensearch-project/notifications/issues/251

**Comment by zhongnansu** [comment]
close as this is duplicate
