### ISSUE TITLE
Add support for other plugins to use notifications without requiring a code change

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/notifications#262]
**Is your feature request related to a problem? Please describe.**
Currently a new plugin requires a code change to enable usage of notifications from an API inter-op

**Describe the solution you'd like**
Ideally an yml setting or api to permission how other plugins can be permission-ed to use other plugin needs to be implemented.

**Describe alternatives you've considered**
1. yml setting, in elasticsearch to list allowed plugin to use a plugin ( lacks i18n support and doesn't feel like the best options) 2. Ideally this should be in the security plugin as part of plugin-plugin permission-ing. 

2.1. Admin users should be able to change this on the fly and not need a cluster reboot.

**Additional context**

**Comment by dbbaughe** [comment]
Just discussion on alternative part:

"lacks i18n support" -> do we even have i18n support in OpenSearch though? I don't mean this as this isn't a good thing to support, but if we already don't support it as of now and this is a bigger issue than just here then I wouldn't count it as a big negative to the approach. Whenever we tackle i18n support (if we do) then there are a lot of things that need to change for all usages of settings that we have.

"Admin users should be able to change this on the fly and not need a cluster reboot" -> If a user goes and installs their own plugin then they have to bring down their OS process anyways to reboot and bring it up, so might not be the worst thing. But, that's assuming you want these to be immutable in the yml setting as opposed to dynamic that can be changed at runtime in the cluster settings API? I do agree we are severely missing security around cluster settings, would be great if the security plugin supported permissions at the namespace level for different settings, i.e. only someone with "ism:settings" permissions can edit ism cluster settings or only someone with "admin" permissions can edit settings under "admin" key in cluster settings. I don't think we have something like that; mainly bringing it up because if we do add toggles into the cluster settings (which we already do in other plugins for security related knobs) then the admins of the cluster need to be aware if they give cluster setting permissions to anyone then they have a lot of control. I'm assuming this is known already though, because anyone with those permissions can basically bring the cluster to a grinding halt and do a lot of damage.

So just other random ideas:

Don't require plugins having to explicitly onboard.. have the notification plugin read in the list of plugins on the cluster and create a "Feature" for each of them to be used? Downside is out of all the plugins installed on cluster a very small minority use Notifications and the Notifications plugin isn't aware of which ones those are. So when users are selecting Features on the UI there is a lot of spam which isn't great.

Have plugins actually register themselves as a Feature on bootstrap.. the most obvious case is if Notifications is an extensible plugin (concrete type of plugin like Job Scheduler).. big downside is plugins now need a hard dependency on Notifications plugin which we wanted to avoid. So is there a way we can do this through common utils somehow? The main issue I'm thinking of for this the order of installation of plugins.. notification plugin isn't guaranteed to be loaded first so might have not loaded whatever is required to do this. But something to explore..

Will try to think of other possibilities..

**Comment by anirudha** [comment]
How does Anomaly Detection use alerting now, may we can follow that pattern?

**Comment by anirudha** [comment]
**Concluding the workflow and simplifications of extensibility of the notification plugin**

1. for Developers using notification plugin: eg. Anomaly detection or any new plugin
1.1 developers can use the api's in common-utils and implement shared functionality and enable yml as a mechanism to enable usage of notification plugin.

2. for user who are using custom developed plugins using notifications plugin
2.1 users install the custom plugin, can enable their plugin to use the notification plugin in elasticsearch.yml
