### ISSUE TITLE
Move development into main branch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#288]
**Is your feature request related to a problem? Please describe.**

OpenSearch projects use main branch for future development. Let's get ourselves out of `develop`?

**Describe the solution you'd like**

Merge develop into main and delete it.

**Comment by zhongnansu** [comment]
@dblock 
Hi, could you suggest a better strategy for this change.
1. Direct merge from develop to main has conflicts.
2. I tried to send a PR from my personal branch which resolves the above conflict(simply just take everything in `develop`), but the PR doesn't allow create a merge commit, only squash is allowed. By doing this, it seems we lose all the commits history? 
![image](https://user-images.githubusercontent.com/32652829/129982256-68627bb9-78bc-4319-a48b-e7b1ad637c36.png)
3. I tried to delete the `main` branch and cut a new branch from `develop`, but since they both are protected branch, it doesn't allow me do delete
4. I tried to force push to main, again protected branch doesn't allow force push

**Comment by zhongnansu** [comment]
I'd suggest that maybe you or someone has the permission, to just delete `main` branch because there's nothing useful there anyways. Then I'll cut a branch named `main` from `develop`.

**Comment by dblock** [comment]
I have access, so enabled the merge and rebase options for now. Let me know when you want them switched back.

(Personally I dislike squash only, but this is org's choice rn.)
