### ISSUE TITLE
[BUG] Security filtering implementation

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/notifications#334]
**Describe the bug**
* Notification plugin currently relies on Alerting security backend filtering setting to determine if the role based filtering need to be done on top of notification artifacts. This creates a tight coupling between the two plugins. As notification is supposed to be used by other plugins like IndexManagement this is confusing for end user. Plugins like IndexManagement and AnomalyDetection which have RBAC have their own plugin specific filtering setting to support filtering on artifacts owned by those plugins.
* Notification plugin for SendNotification call currently [doesn't check any cluster level permission](https://github.com/opensearch-project/common-utils/blob/notification-dev/src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt#L216), but only checks if [user has backend roles if the filtering is enabled](https://github.com/opensearch-project/notifications/blob/88d5793cb55c0a67ee427dea6adb99f00f43a8dd/notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt#L102) 

  * The above implementation doesn't really check anything other than calling user has backend roles, if user has no backed roles it will fail otherwise succeed. At the moment IndexManagement plugin doesn't pass backend roles so all notification actions from IM policies will fail once filtering is enabled. But if index managed plugin is updated to pass backend roles to notification security behavior seems to be broken - i.e If Jane created ISM Policy 'P' and created a channel 'C'. The filter by backend role setting is enabled in the cluster for alerting plugin. Jack another user of ISM doesn't have access to Channel 'C' but to policy 'P'. Jack cannot directly use the channel 'C' to send messages but by associating policy 'P' to an index the user can send notification through channel 'C'. Not sure if this behavior discrepancy of access makes sense i.e Jack has access to channel through ISM but no access through notification plugin directly to use the channel - also as long as Jack knows a channel id they can use that in any policy they are creating and send messages even if they don't have access to the channel
  * If IndexManagement plugin passes the backend roles to notification plugin and the filtering logic in notification plugin is changed to actually filter the channels based on backend role before sending message then also some confusion arises - as ISM user who usually needs cluster permission to execute actions in ISM policy will require to have the corresponding backend role to successfully execute notification action unlike other actions(?)

Using backend role as permission check seems to potentially make things complicated - e.g user Jane today has permission to channel "A" because alerting doesn't have backend role filtering, but enabling filtering in alerting will break Jane's policy managed indices - as all of Jane's managed indices by policy using this channel will fail sending notification with no change done by Jane. For other ISM policy actions that cannot happen - once managed index by a policy is created user object is stored inside policy and only way the managed index job will lose access if the roles lose permissions. With this change filtering is behaving similar to removing permission from role, I am not sure if this intended or a side effect.

**Expected Behavior**
 I think the above makes the filtering behavior more complicated as one plugin resource contains other plugins resource - should notification not support filtering to prevent the additional overhead it can add. Or just use a transport action permission and be an all access or no access till there is more support inside security framework to have Rbac in notification

**Comment by akbhatta** [comment]
@lezzago Please confirm if the proposed behavior is acceptable to alerting plugin. Please also check backward compatibility can be done with the above proposal.

**Comment by akbhatta** [comment]
> > @akbhatta is there going to be another PR to not do the filter when sending the notification based on a setting on top of above PR?
> 
> Yes, I will add notification specific setting on top of this. global setting usage will be done when other plugin creates and starts using it.

#350 #355

**Comment by qreshi** [comment]
I believe this can be closed as the issues previously discussed are no longer the case.

The Notifications plugin does enforce cluster-level API permissions with security enabled. As for RBAC (role-based access) filtering, it can be enabled via the `opensearch.notifications.general.filter_by_backend_roles` setting which will use Alerting's setting as a fallback since the Destinations in Alerting migrating for users upgrading to OpenSearch 2.0 (where the Notifications launched for the first time) will become Notification Channels and we'd like the default to match the level of security they have chosen there.

However, the `opensearch.notifications.general.filter_by_backend_roles` setting in Notifications is not tightly coupled with Alerting's and can be enabled/disabled independently. This works because if RBAC is enabled in Alerting, it'll filter on its own resources (Monitors, etc.). As soon as Alerting makes a request to send a notification, it'll send it to the Notification plugin where it will handle the level of security enabled for the plugin. If RBAC is enabled in Notifications the user asking to send the notification for a channel will need to have API permissions for `SendNotification` and have to match a backend role. If RBAC is not enabled for Notifications, they will just need the API permission to send.

The behaviors above are consistent with what we've been expecting for other plugins within OpenSearch that have onboarded with security. We have had ongoing discussions on standardizing these for developers as well as eventually having a global option to enable RBAC (with the option to override if needed at a plugin level) but that will have to wait until RBAC is consistent and fleshed out in the ecosystem. These things are out of scope for this issue though.

Closing this issue, feel free to re-open if there are any concerns.
