### ISSUE TITLE
[FEATURE] Support Microsoft Teams webhooks

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/notifications#585]
**Is your feature request related to a problem?**
Posting to MSTeams channel through incoming webhook connector

**What solution would you like?**
New channel

**What alternatives have you considered?**
-

**Do you have any additional context?**
The message has to be wrapped in a json object, in it's most basic form it only contains a "text" property:

curl -H 'Content-Type: application/json' -d '{"text": "Hello World"}' <YOUR WEBHOOK URL>

**Comment by praveensameneni** [comment]
Planned for 2.6

**Comment by ict-one-nl** [comment]
Fantastic, many thanks!!

**Comment by xluo-aws** [comment]
Will move to v2.10.0 due to pending security review

**Comment by ict-one-nl** [comment]
Can this be scheduled for the 2.10 release?

**Comment by zhichao-aws** [comment]
> Can this be scheduled for the 2.10 release? I'm reading "Upcoming (Release version TBD)", not sure if that means 2.10

Yes, it is scheduled to be released at 2.10 :)

**Comment by ict-one-nl** [comment]
Cool thanks!

**Comment by DarshitChanpura** [comment]
@zhichao-aws Is this still targeting v2.10? If not, mind tagging it to 2.11?

**Comment by zhichao-aws** [comment]
> @zhichao-aws Is this still targeting v2.10? If not, mind tagging it to 2.11?

@DarshitChanpura We've finished the work and the code is in 2.10 branch now. I think we can mark it as completed.

**Comment by jeferson-cleancloud** [comment]
@mnkugler I did not understand, why this feature was removed from 2.10.0? Is it intended to go for 2.11 ?

**Comment by mnkugler** [comment]
@jeferson-cleancloud Yes apologies moved it to 2.11. I spoke to @xluo-aws and @lezzago and while this feature is accessible through apis, there is still work to be done on the UI side.

**Comment by jeferson-cleancloud** [comment]
@mnkugler tks muck. Looking forward for this feature ;)

**Comment by ict-one-nl** [comment]
Hm this is a shame but butter do it right the first time. Feature would be much appreciated

**Comment by zhichao-aws** [comment]
Seems this ticket has caused some confusion, I'd like to put some clarification here.

Notification plugin is a upstream dependency for other consumer plugins. Users can CRUD notifications channels of all types using API/UI. Notification also provide API for other consumer plugins to send notifications. All above work has already been finished for Microsoft Teams.  Since the channel type is not a parameter to send notification, ideally the consumer plugins can directly use Microsoft Teams channel type. For example, the ISM plugin. However, there is a design flaw in alerting dashboards UI. All available channel types are hard coded in UI so new channel types can not be rendered correctly. And this bug is not specific for Microsoft Teams feature, it exists from 2.0, also influence SES and SNS.

So from the perspective of plugins development, I think we can close this ticket and track the [bug fix ticket](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/713) in roadmap. But from another perspective, like whether users can use Microsoft Teams feature end-2-end from all consumer plugins, it also make sense to mark this ticket as in progress.

**Comment by xluo-aws** [comment]
@ict-one-nl , Hi, Sander, as Zhichao said, the notification plugin will support teams as a new channel type in 2.10. You should be able to config Teams in ISM, the only consumer that's not working is alert plugin due to the bug Zhichao listed above. So this issue is completed in 2.10, sorry for the back and forth change.

**Comment by xluo-aws** [comment]
@mnkugler , I think we can replace 2.11 label with 2.10.

**Comment by ict-one-nl** [comment]
Okay cool thanks. The alert plugin is import of course, looking forward to 2.11 :)

**Comment by xluo-aws** [comment]
> Okay cool thanks. The alert plugin is import of course, looking forward to 2.11 :)

I'm asking alert plugin maintainers if they can fix the bug in 2.11. You can also add your comment there so it get more attention.

**Comment by ict-one-nl** [comment]
Is there any issue for the fix? 2.11 is coming soon from what I understand :)

**Comment by xluo-aws** [comment]
> Is there any issue for the fix? 2.11 is coming soon from what I understand :)

You can ask in https://github.com/opensearch-project/alerting-dashboards-plugin/issues/713.

**Comment by ict-one-nl** [comment]
Done thanks :)
