### ISSUE TITLE
[BUG] Microsoft Office 365 connectors for Teams (including incoming webhook) are deprecated and will be discontinued

### ISSUE THREAD

**Issue by JimReprogle** [opensearch-project/notifications#934]
*What is the bug?*
Microsoft is deprecating the Office 365 connectors for teams, and will require users to utilize the workflow app to post adaptive cards to Teams channels via webhook.

*How can one reproduce the bug?*

1. Go to 'Notifications->Channels->Create Channel'
2. Give a name to your channel
3. Select Channel Type of Microsoft Teams
4. Enter the webhook URL from the Workflow app (not the O365 webhook connector URL. It should look something like:
[https://prod-XX.westus.logic.azure.com:443/workflows/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX](https://prod-xx.westus.logic.azure.com/workflows/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
5. Click "Send Test Message"
6. See the error: [status_exception] Wrong Microsoft Teams url. Should contain "webhook.office.com"

*What is the expected behavior?*
Expected behavior is that the call to the webhook will be able to send a message to the webhook URL. However, the URL is different and does not contain "webhook.office.com", and the expected type of data sent to the webhook is an adaptive card.

*What is your host/environment?*

OS: MacOS
Version: Sonoma 14.5

Do you have any additional context?
Microsoft is deprecating the type of webhook currently used in OpenSearch notifications sent to Microsoft Teams. They will require users to use the Workflow app to receive incoming webhooks, which in turn requires Openseaerch to send adaptive cards.

For reference: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Comment by JimReprogle** [comment]
Moved to OpenSearch Dashboards notifications.

**Comment by bbenouarets** [comment]
The deadline was actually extended. However, the URL of the webhooks must be updated again by December 31, 2024.

If other system administrators are having difficulties locating the affected teams:
I have written a small tool in Golang that uses the Graph API to output the affected teams.

[Teams Webhook Finder](https://github.com/SecNex/teams-webhook-finder)

This has helped us enormously, as Microsoft does not offer its own solution for reading the affected channels and teams. We have over 350 teams in our company, which we would otherwise have had to search through manually.

I hope I could help someone here with this.

Independently of my day job, I would like to create an alternative to the native “incoming webhooks”. Maybe someone will benefit from it.

**Comment by antonspcp** [comment]
Setting up this notification in October 2024-  the URL validation is obselite, it should be removed...
